### ISSUE TITLE
Suggesting my project: Joplin Sync Library 

### ISSUE THREAD

**Issue by khuongduy354** [andrdru/joplin-auto#10]
Hi, this is my GSoC 2024 project: [Joplin Sync Library](https://github.com/khuongduy354/joplin-sync-lib/tree/master)
Which is a wrapper over Joplin synchronization modules, instead of everything packed up into 1 .synchronize() method, we can have .getItems(), .updateItems(),... so it's like a library.  

There's example for detect changes (using Joplin's delta) here: 
[item changes detection demo](https://github.com/khuongduy354/joplin-sync-lib/blob/master/src/sample_app/newItemListener.ts)

Currently, it's supporting FileSystem as sync target, and JoplinServer is coming soon (only a few methods left to be implemented). I know your client is written in Go, but I would love to share the idea, and I wonder if there's anyway that this project my help your client.
Thank you.

**Comment by andrdru** [comment]
Hi, @khuongduy354, thanks for sharing, nice project.

My project is a client library for Joplin based on s3 target and webClipper API. It impements basic sync protocol. I extract this lib to package, so you can reuse it. Hope it may be useful for you too.

I'm closing your issue sinse it was only for sharing purposes.
Feel free to contact if you have any questions
